easy_admin:
    site_name: Bibliotheque
    entities:
        # List the entity class name you want to manage
        - App\Entity\Author
        - App\Entity\Book
        - App\Entity\Editor
        - App\Entity\Genre
        - App\Entity\Nationalite